# Numpy Basics

In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3])

In [3]:
arr = np.array([[2, 4, 6], [1.2, 5, 9]])
arr

array([[2. , 4. , 6. ],
       [1.2, 5. , 9. ]])

In [4]:
# Number of dimentions

arr.ndim

2

In [5]:
# Shape of the array (rows, columns)

arr.shape

(2, 3)

In [6]:
# Array data type - Default = int32

arr.dtype

dtype('float64')

In [7]:
# Length of the array - total number of elements

arr.size

6

In [8]:
# Number of bytes

arr.itemsize

8

In [9]:
# Number of bytes consumed

arr.nbytes

48

# Numpy is faster than Python

In [10]:
import sys

In [11]:
py_ar = [2, 4, 8, 10]

In [12]:
np_ar = np.array([2, 4, 8, 10])

In [13]:
sys.getsizeof(1) * len(py_ar)

112

In [14]:
np_ar.itemsize * np_ar.size   # same as np_ar.nbytes

32

In [15]:
## Numpy array - takes less size than that of Python array
## Numpy array - No typecheking required while iterating through objects
## Numpy array - Utilizes contiguos memory (memory blocks are not scattered)
## Numpy array - objects are fixed type only stores the bytes that represent the value (while in list - size, reference count, object type, object value)

# Array Creation: Using python objects

In [16]:
listarr = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [17]:
listarr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Array Creation: Using intrinsic numpy creation object

In [18]:
# creates a array with zero elements

zeros = np.zeros((2,5))  
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [19]:
# similar to python range function

rng = np.arange(15)
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [20]:
# using full (shape), value

np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [21]:
# using ones - All 1s matrix

np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [22]:
# equally linear space between 1,5 for 12 elements

lspace = np.linspace(1,5,12)
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [23]:
emp = np.empty((3,6))
emp

array([[0.00000000e+000, 2.35541534e-312, 2.41907520e-312,
        2.14321575e-312, 2.46151512e-312, 2.31297541e-312],
       [2.35541533e-312, 2.05833592e-312, 2.22809558e-312,
        2.56761491e-312, 2.48273508e-312, 2.05833592e-312],
       [2.05833592e-312, 2.29175545e-312, 2.07955588e-312,
        2.14321575e-312, 0.00000000e+000, 0.00000000e+000]])

In [24]:
emp_like = np.empty_like(lspace)
emp_like

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [25]:
# Identity matrix - is for creating square matrix (nxn)

ide = np.identity(5)
ide

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# Array Creation: Using special function

In [26]:
# array filled with random decimal values between 0 and 1 - (shape)

a = np.random.random((2,2))
print(a)

np.random.random_sample(a.shape)

[[0.23593324 0.24180969]
 [0.44984357 0.28869942]]


array([[0.92817614, 0.55958406],
       [0.76299484, 0.23204231]])

In [27]:
# array filled with random integer values between 0 and 1 - (shape)

np.random.randint(7, size=(3,3))

array([[6, 3, 1],
       [3, 5, 4],
       [5, 4, 6]])

# Copy array

In [28]:
# This will change the original array as well

a = np.array([1, 2, 3])
b = a
b[0] = 50
print(b)


# This will not change the original array as well

x = np.array([1, 2, 3])
y = a.copy()
y[0] = 100
print(x)


[50  2  3]
[1 2 3]


# Accessing /Changing specific elements, rows, columns

In [29]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [30]:
# Get a speicifc element [row][col]

print(a[0][4])
print(a[1][-1])

5
14


In [31]:
# Get a specific row

print(a[1, :])
print(a[0, :])

[ 8  9 10 11 12 13 14]
[1 2 3 4 5 6 7]


In [32]:
# Get a specific colum

print(a[:, 2])
print(a[:, -1])

[ 3 10]
[ 7 14]


In [33]:
# Get specific elements in arrat [start_index:end_index:step_size]

print(a[0, 1:-1:1])
print(a[1, 0:-1:2])


[2 3 4 5 6]
[ 8 10 12]


In [34]:
# Changing values

a[1, 2] = 20
print(a)

a[:, 2] = [1, 2]
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 20 11 12 13 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 13 14]]


### 3D array example

In [35]:
# creating a 3D array

a = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(a)

# Accessing elements

print(a[0, 0, 1])
print(a[:, 1, :])

# changing element values

a[:, 1, :] = [[10, 10], [20, 20]]
print(a)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
2
[[3 4]
 [7 8]]
[[[ 1  2]
  [10 10]]

 [[ 5  6]
  [20 20]]]


# Array shape conversion

In [36]:
arr = np.arange(20)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [37]:
# the values inside reshape should be multiple of arr size (2*10=20)

arr.reshape(2,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [38]:
# the values inside reshape should be multiple of arr size (5*4=20)

reshaped_arr = arr.reshape(5,4)
reshaped_arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [39]:
arr.ravel()  # creates an 1-D array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [40]:
reshaped_arr.flat  # returns an iterator

In [41]:
# iterating over the flat object

for items in reshaped_arr.flat:
    print(items)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


# Numpy axis

In [42]:
x = [[1,2,3],[4,5,6],[7,8,9]]

In [43]:
ar = np.array(x)

In [44]:
ar.sum(axis=0)  # Gives sum of each rows (accessing rows)

array([12, 15, 18])

In [45]:
ar.sum(axis=1)  # Gives sum of each columns (accessing columns)

array([ 6, 15, 24])

In [46]:
ar.size

9

In [47]:
one = np.array([1, 2, 3, 0])

In [48]:
one.argmax()  # Returns index of maximum element

2

In [49]:
one.argmin()  # Returns index of minimum element

3

In [50]:
one.argsort()  # rerturns how the elements should be sorted

array([3, 0, 1, 2])

In [51]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [52]:
arr.argmin()  # it flattens the array abd then returns the min value index

0

In [53]:
arr.argmax()  # it flattens the array abd then returns the max value index

8

In [54]:
arr.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [55]:
arr.argmax(axis=0)  # returns the max value index for axis 0 (rows) - 7,8,9

array([2, 2, 2])

In [56]:
arr.argmax(axis=1)  # returns the max value index for axis 1 (columns) - 3,6,9

array([2, 2, 2])

In [57]:
arr.argmin(axis=0)  # returns the min value index for axis 0 (rows) - 1,2,3

array([0, 0, 0])

In [58]:
arr.argmin(axis=1)  # returns the min value index for axis 1 (column) - 1,4,7

array([0, 0, 0])

In [59]:
arr.argsort(axis=0)

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]])

In [60]:
arr.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

# Mathematical

In [61]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [62]:
a + 2

array([3, 4, 5, 6])

In [63]:
a - 2

array([-1,  0,  1,  2])

In [64]:
a * 2

array([2, 4, 6, 8])

In [65]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [66]:
a // 2

array([0, 1, 1, 2])

In [67]:
a % 2

array([1, 0, 1, 0])

In [68]:
ar1 = np.array([[1,2,3], [4,5,6], [7,1,1]])

In [69]:
ar2 = np.array([[1,2,1], [4,1,6], [8,1,1]])

In [70]:
ar1, ar2

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 1, 1]]),
 array([[1, 2, 1],
        [4, 1, 6],
        [8, 1, 1]]))

In [71]:
ar1 + ar2

array([[ 2,  4,  4],
       [ 8,  6, 12],
       [15,  2,  2]])

In [72]:
ar1*ar2

array([[ 1,  4,  3],
       [16,  5, 36],
       [56,  1,  1]])

In [73]:
ar1-ar2

array([[ 0,  0,  2],
       [ 0,  4,  0],
       [-1,  0,  0]])

In [74]:
ar1%ar2

array([[0, 0, 0],
       [0, 0, 0],
       [7, 0, 0]])

In [75]:
np.sqrt(ar1)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 1.        ]])

In [76]:
ar1.sum()

30

In [77]:
ar1.max()

7

In [78]:
ar1.min()

1

# Find elements

In [79]:
ar1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 1]])

In [80]:
np.where(ar1>5)  # returns a tuple of arrays which indices elements are greater than 5

(array([1, 2]), array([2, 0]))

In [81]:
np.count_nonzero(ar1)  # return elements count which are not zero

9

In [82]:
np.nonzero(ar1)  # returns a tuple for each axis where element is not zero

(array([0, 0, 0, 1, 1, 1, 2, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1, 2]))

# Functions

In [83]:
ar = np.array([[1,2,3],[4,5,6],[7,8,9]])
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [84]:
# Used to tranpose the array
transpose = ar.T
transpose

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])